---
version: '3'

services:
  pydata-latest:
    build:
      context: ../build/latest
      dockerfile: Dockerfile
    image: dceoy/pydata:latest
  pydata-dnn-gpu:
    build:
      context: ../build/dnn-gpu
      dockerfile: Dockerfile
    image: dceoy/pydata:dnn-gpu
  pydata-dnn-cpu:
    build:
      context: ../build/dnn-cpu
      dockerfile: Dockerfile
    image: dceoy/pydata:dnn-cpu
