---
version: '3'

services:
  pydata:
    build:
      context: ../build/latest
      dockerfile: Dockerfile
    image: dceoy/pydata:latest
  tf-cpu:
    build:
      context: ../build/tf-cpu
      dockerfile: Dockerfile
    image: dceoy/pydata:tf-cpu
  tf-gpu:
    build:
      context: ../build/tf-gpu
      dockerfile: Dockerfile
    image: dceoy/pydata:tf-gpu
  dnn-cpu:
    build:
      context: ../build/dnn-cpu
      dockerfile: Dockerfile
    image: dceoy/pydata:dnn-cpu
  dnn-gpu:
    build:
      context: ../build/dnn-gpu
      dockerfile: Dockerfile
    image: dceoy/pydata:dnn-gpu
