---
version: '3'

services:
  nbconvert:
    container_name: nbconvert
    image: dceoy/pydata:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - jupyter
    command:
      - nbconvert
      - --to=notebook
      - --ExecutePreprocessor.timeout=-1
      - --execute
      - --inplace
      - --ExecutePreprocessor.kernel_name=python
