---
version: '3'

services:
  pydata:
    container_name: pydata
    image: dceoy/pydata:latest
    user: ${UID}:${GID}
    userns_mode: host
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - jupyter
    command:
      - notebook
      - --port=8888
      - --ip=0.0.0.0
      - --notebook-dir=.
      - --allow-root
      - --no-browser
