---
version: '3'

services:
  pydata:
    container_name: pydata
    build:
      context: ../build/latest
      dockerfile: Dockerfile
    image: dceoy/pydata:latest
    user: ${UID}:${GID}
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - jupyter
    command:
      - notebook
      - --port=8888
      - --ip=0.0.0.0
