---
version: '3'

services:
  pydata:
    container_name: pydata
    build:
      context: ${PWD}
    image: dceoy/pydata:latest
    user: ${UID}:${GID}
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - python
